### ISSUE TITLE
Invalid format of Authorization header

### ISSUE THREAD

**Issue by MnM** [creichert/http-client-auth#1]
According to RFCs 2617 and 2616, the Authorization header "elements" have to be comma-delimited. Example from the spec:

```
Authorization: Digest username="Mufasa",
                 realm="testrealm@host.com",
                 nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
                 uri="/dir/index.html",
                 response="6629fae49393a05397450978507c4ef1"
```

Header sent by http-client-auth:

```
Authorization: Digest username="Mufasa"
                 realm="testrealm@host.com"
                 nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093"
                 uri="/dir/index.html"
                 response="6629fae49393a05397450978507c4ef1"
```

Note the missing commas between elements.

**Comment by creichert** [comment]
Thanks for the patch, I mentioned this in the other issue but:

> Just FYI, this repository is originally a fork of https://hackage.haskell.org/package/http-client-auth. 
> I've had plans to rename it since I've applied fixes and changes too. I will be happy to merge fixes 
> and make the work available, though.

You would have to contact the author directly of that package to get these patches there but my understanding is he may not be active.
