### ISSUE TITLE
Authorization field uri (request-uri) shouldn't contain rel_path

### ISSUE THREAD

**Issue by MnM** [creichert/http-client-auth#2]
http-client-auth appends the query part to the Authorization "uri" field. RFC2617 describes this field as follows:

```
    digest-uri       = "uri" "=" digest-uri-value
    digest-uri-value = request-uri   ; As specified by HTTP/1.1
```

RFC2616 (HTTP/1.1):

```
    Request-URI    = "*" | absoluteURI | abs_path | authority
    http_URL = "http:" "//" host [ ":" port ] [ abs_path [ "?" query ]]
```

Thus, the "uri" field should simply contain the contents of `path :: Request -> ByteString`.

**Comment by creichert** [comment]
Thanks for the report, and the patches.

Just FYI, this repository is originally a fork of https://hackage.haskell.org/package/http-client-auth. I've had plans to rename it since I've applied fixes and changes too. I will be happy to merge fixes and make the work available, though.
